language: python
dist: xenial
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  api_key:
    secure: JhJjxFBkrpZvlzEELJYErskvKSzo5U6mE9uhaBIt3gZ9IBiqbKLTwJKltjufiy7qnBNCrQNZAGByEQq7UrrGBT7dOLceJ++yikUqx0o9UNUuw/LxmSc/v6LdxwAY9hniOaArcSE5DsXD8Hef+BQgXOlYJt+VDKcuKIud535KBbgO0TPO9URskqFZt32bbTNWXWBTR5gElykRn8VnMrT8FH+XN3Tz1riZo1h6t0om0og6NBZ81ATyvQH1GgTfuXTi7EcxwMe8+6rYSNPJj/zu5d2OIdXGR5Q0WfK+0ckeUTzTd/ZBn8A/dgjMtB2rgCZJqMZ2uqaOhgVQjjDR3jMdA0W+fu1FsW8cyJoGx6HGvwxYk0S0JiAlQAcdxa3PUVEQHmYjprpUrfWg4Ead6S3j0UPLAjG6YuD4bRnxil6dBkjYZQZdnwys7u7jnpFKR7YYHJVFRqPPqhlw/Fc3rId9FpdEo2hj42pGtEcNxkXi6gG02m6qxZqaV+/2W8tsdGqLhkUJdZYoEmErJstJi1FdvMS4YrQPAucWHSAFgDzZ4zWysPMyIpGHf+B6lUdTEdo4Qq+0/L2E2rJoeq10hlpnoCFKoFlQOOk0hI0EumPG5z9XZxCezgHXNIJk6riFNkde7ZmriMDS3LeNB0jyg8ZLB2cAGMTylPsyNBOOMyYl1P8=
